### ISSUE TITLE
Sled Jig Machining

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#16]
The sled jig ([drawing], [part]) aligns the rail sled  (issue #7) on the [fin can][assembly] and on the RCS module. It's probably the most straightforward part in the airframe yet, since everything is planes and holes at right angles with some chamfers and countersinks. The CAD is all done and we probably have suitable stock in the rocket closet. Someone just needs to make it. Perhaps @JacobTiller or @SaturnVF1?

![image](https://cloud.githubusercontent.com/assets/16861664/24746367/b6e2cefe-1a6d-11e7-96d0-fd7603a872a7.png)
![image](https://cloud.githubusercontent.com/assets/16861664/24746396/cffe4922-1a6d-11e7-8d87-66aefc0ec251.png)
![image](https://cloud.githubusercontent.com/assets/16861664/24746486/23b171a2-1a6e-11e7-8ada-7f636bb9e53f.png)

[drawing]: https://github.com/psas/lv3.0-airframe/blob/master/cad/railSled/sledJig.pdf
[part]: https://github.com/psas/lv3.0-airframe/blob/master/cad/railSled/sledJig.SLDPRT
[assembly]: https://github.com/psas/lv3.0-airframe/blob/master/cad/finCan/finCanLayup.SLDASM

**Comment by SaturnVF1** [comment]
Is it aluminum? If Jake doesn't have a chance to use a real shop I could probably do it in the LID.

**Comment by Joedang** [comment]
Yup, it's aluminum. The giant "LV3" blocks are probably big enough, but cutting off a piece might be obnoxious.

**Comment by Joedang** [comment]
Reason for closing: @SaturnVF1 made the thing.
