### ISSUE TITLE
Missing Fillet in Spider Drawing

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#18]
The fillet between the arms and feet, if you will, of the spider isn't called out in [this drawing.](https://github.com/psas/lv3.0-airframe/blob/master/cad/finCan/spider.pdf) (Most obvious in the 3D view on sheet 1 and in section C.) Someone (probably me, next time I'm on SolidWorks) should add that.

**Comment by IanZabel** [comment]
I added the callout to the leg-feet fillet (section D) on sheet 3 just below the existing section C view. Let me know if you want any changes made and cant make it to Solidworks anytime soon.
