### ISSUE TITLE
Achieving suborbital with solids.

### ISSUE THREAD

**Issue by rgregoryclark** [psas/lv3.0-airframe#20]
Amateur groups have sent flights to the Karman line of 100 km for suborbital space, but no university team has accomplished it yet. It might be doable by liqhtweighting the casings used on your solid motor  launch vehicles by replacing the aluminum with carbon fiber.

 I saw on your web pages you have used carbon fiber airframes. But what's more than that that needs to be done is replace the actual casing on the motors with carbon fiber. For example, the N-class solid motor used on your LV 2.2, you could have it delivered from the manufacturer with the propellant in just its sleeve and you would make the casing for it in carbon fiber.

 If the one N-class motor with carbon fiber casing does not reach suborbital space, you almost certainly would be able to reach it in two stages. The second stage again would replace the aluminum casing with carbon fiber.

  Bob Clark

**Comment by andrewgreenberg** [comment]
Hi Bob! See my response to your email on the PSAS list. I'm closing this issue.
