### ISSUE TITLE
Umbilical + switch ring

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#23]
## Problem
We are legally required to have some way to enable/disable the launchy bits after the rocket's assembled. Also, after L-13, we will probably want to be able to provide power and data up until the launch. 

## Suggested Solution
Create a ring with the usual M/F interfaces with holes for switches and a power/data umbilical connection.

**Comment by JSRoland** [comment]
Hey Joe,
There is a repo for this project here: https://github.com/psas/sw-cad-airframe-umbilical-disconnect

**Comment by Joedang** [comment]
Oh yeah, that's why it seemed so familiar... :upside_down_face:
