### ISSUE TITLE
Order motor

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#26]
## Problem
We don't have the flamey bit that makes us go to space.

## Suggested Solution
Get a Cesaroni 21062-O3400-IM.

**Comment by andrewgreenberg** [comment]
Nope! Won't fit in our current motor casing, and it's not worth it to upgrade to a 6XL casing on our first flight. So we bought another CTI N2501. Perhaps this summer's flight we'll upgrade?
