### ISSUE TITLE
Machining fin jigs

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#5]
The fin jigs ([middle](../tree/master/cad/finCan/fin_jig_mid.SLDPRT) and [ends](../tree/master/cad/finCan/fin_jig_top_bottom2.SLDPRT)) are designed, but need a few things to come into meatspace. 
- [x] There needs to be a 2D technical drawing made of the part. (Not strictly necessary, but VERY handy.)
- [X] The aluminum plates must be acquired.
- [X] There needs to be CAM done for the particular machine it will be made on.
- [X] Someone needs to do the actual machining.  
_That's Peter._
- [X] A 1/16" cutter must be purchased. (2 flutes strongly preferred)

This part requires a 1/16th inch end mill and is roughly 18 inches square, I think. It's designed as a purely 2D part.

**Comment by petermccloud** [comment]
@Joedang I've been shopping cutters and there are no 1/16" cutters that have a 1/4" shank (since my machine only takes 1/4" and 1/2" shanks). The smallest cutter size for a 1/4" shank is 1/8". So we either need to do this on a different machine or re-design the part.

**Comment by Joedang** [comment]
Some of the cutters [here](http://www.2linc.com/endmills/endmills_ballnose_1-16.htm), [here](http://www.2linc.com/endmills_aluminum_2fl_std.htm), and [here](http://www.2linc.com/endmills_aluminum_1fl_std.htm) fit our needs. There's also [this listing](http://www.ebay.com/itm/Kyocera-T0625O188-3F-Square-End-Mill-0-0625-1-16in-Dia-1-4in-Shank-AX-Coated-/332042057753?hash=item4d4f3fb819:g:vQEAAOSwa~BYeUuT) on ebay, but I'm not sure how well 3 flutes would work with aluminum when it's that small.

**Comment by petermccloud** [comment]
Awesome, thanks for finding this. Got the bits ordered, they should show up on Thursday.

**Comment by Joedang** [comment]
Reason for closing: @petermccloud made the thing.
