### ISSUE TITLE
Fixing and Machining the Rail Sled

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#7]
This task doesn't have anyone associated with it, and is open to anyone willing to do some machining. 

Remaining tasks:
- [X] Tweak the dimensions of the rail sled to better fit the rail.
- [X] Remake the HDPE layers.
- [X] Determine the appropriate thickness of the aluminum base.
- [X] Remake the aluminum base.
- [X] Confirm loose fit with the rail.  
_requires a small amount of 3-in-1 oil_
- [X] Machine a second set of parts for the upper sled.

This is a series of 2D parts that bolt together. They could be done on a 2-axis CNC mill or a manual mill with a rotary table and perhaps a DRO. It's three layers of HDPE and one layer of aluminum. 

A prototype for the rail sled has already been made, but the dimensions were off and there were some issues with the surface finish of the aluminum base. This would be a good project for an ME undergrad or anyone with access to a machine shop. 

The [CAD files are here](../tree/master/cad/railSled), along with the CAM used to machine the prototype. There should be plenty of suitable aluminum and HDPE in the rocket room for this.

**Comment by JacobTiller** [comment]
I've updated the cad files (with solid works files and drawings) and pushed them to Git.  I have also made a prototype in the machine shop on a manual mill.  The part needs to be checked out to see if it needs any tweaking before I build the second one.

**Comment by Joedang** [comment]
With that little bit of oil, it seemed to slide pretty well. I'd say go ahead with the second one.

**Comment by Joedang** [comment]
Reason for closing: @JacobTiller made the thing.
