### ISSUE TITLE
Sanding

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-airframe#9]
Although we have enough modules for a whole airframe at this point, they all have a rough surface. The outer adhesive covering needs to be sanded to ~1500 grit. This is mostly a warm-body task that involves basic safety with dust control and a lathe. 

@kablakeman has already done some work on this. So, if you would like to take this on, you should talk to him about it.
## Requirements
- Smooth to 0.001" surface roughness (ignoring micro-voids in the adhesive)
- Do not sand into the CF! (leave some patches unsanded, if necessary)
- Also do the nosecone

## Intended solution

Fix one end of the module on a dummy ring and attach a spider to the other end. Chuck the dummy ring in the lathe and use a _live_ center to hold the spider. Use sandpaper to grind down the surface. Use 320 grit to take off the "goosebumps," 800 to flatten it, and 1500 to finish. 

For the radome, spray the surface with high-temp paint (_not_ matching the color of the radome) before sanding. Move to the 1500 when you get to the point where the paint only remains in the creases. This might be a good optional step for the CF modules too. 

It may end up that the lathe won't work for this, in which case they will have to be sanded by hand. This process should be tested on the 18" CF module _before_ the radome or 24" modules, since the 18" CF is not mission-critical. 
## Additional Safety

Talk to Alex Chally about appropriate safety measures. Don't put your hand on the rotating part (!!!), tension a piece of sandpaper instead. Use plenty of water to mitigate dust. Put down towels under the part. Wear a respirator for good measure.

**Comment by Joedang** [comment]
## Update
The current plan is that @kablakeman will make some wood sections (below) that will bolt to the layup table.

![image](https://cloud.githubusercontent.com/assets/16861664/24747220/8037820c-1a70-11e7-9dd7-4d4972f2e5fb.png)

These sections will connect to a spider via a threaded rod. So, we can set up a low-torque lathe-like thing (below). 

![image](https://cloud.githubusercontent.com/assets/16861664/24747464/433f51e4-1a71-11e7-92ec-d6400b827838.png)

#### Why this is a good idea
* We can have someone control the rate of rotation with one hand on the trigger of a drill while they control the pressure/position of an abrasive pad with the other hand (more control). 
* This is probably less risky than doing it on a lathe. 
* We don't need to worry about ruining any expensive equipment. 
* We don't need any special room access to do this.

**Comment by andrewgreenberg** [comment]
5/5 Andrews agree this is a very good idea, especially since we can use this for all the modules at our leisure.

**Comment by kablakeman** [comment]
I uploaded a caveman-esque-CAD of the sanding module I am working on. Comments and criticisms appreciated. Sorry about the DWG. I'm a heathen.

**Comment by Joedang** [comment]
I have a few comments.

* Do you have any other formats you can export to like STEP, IGES, or PDF? DWG is essentially unopenable without AutoCAD. 
* I would make both ends of the holes flat, to make them easy to clamp with bolts.
* The [spider](https://github.com/psas/lv3.0-airframe/blob/master/cad/finCan/spider.pdf) uses a [3/8" threaded](https://www.fastenal.com/content/product_specifications/TROD.304.pdf) rod to attach to the motor. If you make the hole for the shaft 7/8", we can use a [1604 bearing](https://www.bearingworks.com/bearing-sizes/#1600-inch-series) on either end to hold the rod. 
* What are you planning to use to make the ends? I'd assumed it would be wood. 3D printing or laser cutting might also work. 
* Is there a reason for making the outer arch concentric with the hole?

**Comment by Joedang** [comment]
# Yet Another Update On the Sanding Rig

### what didn't work
The threaded rod ended up being kind of sucky. Since there was some clearance between the rod and the inside of the bearings, it would walk along them as it spun. After a few seconds, the module would just rub against the sides of the rig. We couldn't fix things to the threaded rod easily, even when locking nuts against each other. (It probably would have been fine, if the nuts were opposing an axial load, but they were opposing circumferential loads.)

### changes made
We replaced the threaded rod and nuts with a keyed shaft. Collars on the shaft keep the rotating assembly and keys from jiggling out of place. A key at the end of the shaft is used to transfer torque from the drill. 

### use procedure
A plastic curtain needs to be behind the rig when in use, since it sprays water/adhesive slurry in the radial direction. For the same reason, the operator should wear coveralls (preferably disposable), gloves, goggles, and a dust mask. 

With one hand, control the drill. Spray the module with water (squirt/spray bottle). With the other hand, press the sandpaper to the module. Stand so that the spray hits your coveralls. Use both the drill trigger and sandpaper pressure to moderate the speed. Apply more water as necessary.

Sand with 320 grit paper until you read the carbon fiber (small patches of the surface will appear black instead of blue/green). Use a dry paper towel to wipe away the slurry when checking your progress.  Finish with a light pass of 800 grit. 

Be sure to clean up any slurry that sprayed the surrounding area and dispose of the curtain, coveralls, gloves, towels, and sandpaper. 

# Remaining LV3a Sanding Jobs
### critical path
- [ ] nosecone (hand-sand; don't use the rig)

### non-critical path
- [ ] radome module (sand with 800 grit, coat with contrasting paint, sand down to adhesive layer)
- [ ] 18" module
- [ ] 24" module

**Comment by Joedang** [comment]
Everything except for the uncoated and "dragonscale" modules have been sanded. Since they aren't going to be used for L-13, I'm going to consider this done.
